# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverme', '0002_auto_20180315_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='destLat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='destLon',
        ),
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.TextField(null=True),
        ),
    ]
